10:16:54 -     INFO - wally           - All info would be stored into /home/mosorio/wally/wally_results/worthy_serval
10:16:54 -     INFO - wally           - Start discover_stage
10:16:54 -     INFO - wally           - Start reuse_vms_stage
10:16:54 -     INFO - wally           - Start log_nodes_statistic_stage
10:16:54 -     INFO - wally           - Found 1 nodes total
10:16:54 -    DEBUG - wally           - Found 1 nodes with role testnode
10:16:54 -     INFO - wally           - Start save_nodes_stage
10:16:54 -     INFO - wally           - Start connect_stage
10:16:54 -     INFO - wally           - Connecting to nodes
10:16:55 -     INFO - wally           - All nodes connected successfully
10:16:55 -     INFO - wally           - Start run_tests_stage
10:16:55 -    DEBUG - wally           - Run preparation
10:16:56 -    DEBUG - wally           - SSH:138.219.231.195:2121 Exec 'sudo apt-get -y install screen fio'
10:17:03 -     INFO - wally           - Prefilling file /tmp/test.raw
10:17:04 -    DEBUG - wally           - SSH:138.219.231.195:2121 Exec 'sudo fio --name=xxx --filename=/tmp/test.raw --direct=1 --bs=4m --size=5120m --rw=write'
10:17:52 -     INFO - wally           - Initiall fio fill bw is 106 MiBps for this vm
10:17:52 -     INFO - wally           - Entire test should takes aroud: 0:16:30 and finished at 10:34:22
10:17:52 -     INFO - wally           - Will run hdd_rwx4kth1 test
10:17:52 -     INFO - wally           - Test should takes about 0:02:30. Should finish at 10:20:22, will wait at most till 10:25:22
10:17:53 -    DEBUG - wally           - SSH:138.219.231.195:2121 Exec 'screen -S test -d -m sudo bash /tmp/wally/worthy_serval/io/cmd.sh'
10:18:00 -    DEBUG - wally           - Test on node 138.219.231.195_2121 is finished
10:18:00 -    ERROR - wally           - No exit code file found on 138.219.231.195_2121. Looks like process failed to start
10:18:00 -     INFO - wally           - Reconnectiong, sleeping 30s and retrying
10:18:32 -    DEBUG - wally           - SSH:138.219.231.195:2121 Exec 'screen -S test -d -m sudo bash /tmp/wally/worthy_serval/io/cmd.sh'
10:20:29 -    DEBUG - wally           - Test on node 138.219.231.195_2121 is finished
10:20:30 -    ERROR - wally           - During run_tests_stage
Traceback (most recent call last):
  File "wally/main.py", line 125, in log_stage
    yield
  File "wally/main.py", line 277, in main
    stage(cfg, ctx)
  File "wally/run_test.py", line 481, in run_tests_stage
    for tp, res in run_tests(cfg, test_group, ctx.nodes):
  File "wally/run_test.py", line 242, in run_tests
    res = test_cls(test_cfg).run()
  File "wally/suits/io/fio.py", line 777, in run
    test_res = res.get_params_from_fio_report()
  File "wally/suits/io/fio.py", line 281, in get_params_from_fio_report
    total_ios = [self.raw_result[node]['jobs'][0]['mixed']['total_ios'] for node in nodes]
KeyError: 'total_ios'
10:20:30 -     INFO - wally           - Start disconnect_stage
10:20:30 -    DEBUG - wally           - Start utils.cleanup
10:20:30 -     INFO - wally           - All info stored into /home/mosorio/wally/wally_results/worthy_serval
10:20:30 -    ERROR - wally           - Tests are failed. See detailed error above
