12:36:56 -     INFO - wally           - All info would be stored into /var/wally_results/tamest_charlotte
12:36:56 -     INFO - wally           - Start discover_stage
12:37:35 -     INFO - wally           - Start reuse_vms_stage
12:37:35 -     INFO - wally           - Start log_nodes_statistic_stage
12:37:35 -     INFO - wally           - Found 7 nodes total
12:37:35 -    DEBUG - wally           - Found 3 nodes with role ceph-mon
12:37:35 -    DEBUG - wally           - Found 3 nodes with role ceph-osd
12:37:35 -    DEBUG - wally           - Found 1 nodes with role testnode
12:37:35 -     INFO - wally           - Start save_nodes_stage
12:37:35 -     INFO - wally           - Start connect_stage
12:37:35 -     INFO - wally           - Connecting to nodes
12:37:47 -    ERROR - paramiko.transport - Exception: Error reading SSH protocol banner
12:37:47 -    ERROR - paramiko.transport - Traceback (most recent call last):
12:37:47 -    ERROR - paramiko.transport -   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1710, in run
12:37:47 -    ERROR - paramiko.transport -     self._check_banner()
12:37:47 -    ERROR - paramiko.transport -   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1858, in _check_banner
12:37:47 -    ERROR - paramiko.transport -     raise SSHException('Error reading SSH protocol banner' + str(e))
12:37:47 -    ERROR - paramiko.transport - SSHException: Error reading SSH protocol banner
12:37:47 -    ERROR - paramiko.transport - 
12:37:50 -    ERROR - paramiko.transport - Exception: Error reading SSH protocol banner
12:37:50 -    ERROR - paramiko.transport - Traceback (most recent call last):
12:37:50 -    ERROR - paramiko.transport -   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1710, in run
12:37:50 -    ERROR - paramiko.transport -     self._check_banner()
12:37:50 -    ERROR - paramiko.transport -   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1858, in _check_banner
12:37:50 -    ERROR - paramiko.transport -     raise SSHException('Error reading SSH protocol banner' + str(e))
12:37:50 -    ERROR - paramiko.transport - SSHException: Error reading SSH protocol banner
12:37:50 -    ERROR - paramiko.transport - 
12:37:51 -    ERROR - paramiko.transport - Exception: Error reading SSH protocol banner
12:37:51 -    ERROR - paramiko.transport - Traceback (most recent call last):
12:37:51 -    ERROR - paramiko.transport -   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1710, in run
12:37:51 -    ERROR - paramiko.transport -     self._check_banner()
12:37:51 -    ERROR - paramiko.transport -   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1858, in _check_banner
12:37:51 -    ERROR - paramiko.transport -     raise SSHException('Error reading SSH protocol banner' + str(e))
12:37:51 -    ERROR - paramiko.transport - SSHException: Error reading SSH protocol banner
12:37:51 -    ERROR - paramiko.transport - 
12:37:53 -    ERROR - paramiko.transport - Exception: Error reading SSH protocol banner
12:37:53 -    ERROR - paramiko.transport - Traceback (most recent call last):
12:37:53 -    ERROR - paramiko.transport -   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1710, in run
12:37:53 -    ERROR - paramiko.transport -     self._check_banner()
12:37:53 -    ERROR - paramiko.transport -   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1858, in _check_banner
12:37:53 -    ERROR - paramiko.transport -     raise SSHException('Error reading SSH protocol banner' + str(e))
12:37:53 -    ERROR - paramiko.transport - SSHException: Error reading SSH protocol banner
12:37:53 -    ERROR - paramiko.transport - 
12:37:57 -    ERROR - paramiko.transport - Exception: Error reading SSH protocol banner
12:37:57 -    ERROR - paramiko.transport - Traceback (most recent call last):
12:37:57 -    ERROR - paramiko.transport -   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1710, in run
12:37:57 -    ERROR - paramiko.transport -     self._check_banner()
12:37:57 -    ERROR - paramiko.transport -   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1858, in _check_banner
12:37:57 -    ERROR - paramiko.transport -     raise SSHException('Error reading SSH protocol banner' + str(e))
12:37:57 -    ERROR - paramiko.transport - SSHException: Error reading SSH protocol banner
12:37:57 -    ERROR - paramiko.transport - 
12:38:02 -    ERROR - paramiko.transport - Exception: Error reading SSH protocol banner
12:38:02 -    ERROR - paramiko.transport - Traceback (most recent call last):
12:38:02 -    ERROR - paramiko.transport -   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1710, in run
12:38:02 -    ERROR - paramiko.transport -     self._check_banner()
12:38:02 -    ERROR - paramiko.transport -   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1858, in _check_banner
12:38:02 -    ERROR - paramiko.transport -     raise SSHException('Error reading SSH protocol banner' + str(e))
12:38:02 -    ERROR - paramiko.transport - SSHException: Error reading SSH protocol banner
12:38:02 -    ERROR - paramiko.transport - 
12:38:04 -    ERROR - paramiko.transport - Exception: Error reading SSH protocol banner
12:38:04 -    ERROR - paramiko.transport - Traceback (most recent call last):
12:38:04 -    ERROR - paramiko.transport -   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1710, in run
12:38:04 -    ERROR - paramiko.transport -     self._check_banner()
12:38:04 -    ERROR - paramiko.transport -   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1858, in _check_banner
12:38:04 -    ERROR - paramiko.transport -     raise SSHException('Error reading SSH protocol banner' + str(e))
12:38:04 -    ERROR - paramiko.transport - SSHException: Error reading SSH protocol banner
12:38:04 -    ERROR - paramiko.transport - 
12:38:05 -    ERROR - paramiko.transport - Exception: Error reading SSH protocol banner
12:38:05 -    ERROR - paramiko.transport - Traceback (most recent call last):
12:38:05 -    ERROR - paramiko.transport -   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1710, in run
12:38:05 -    ERROR - paramiko.transport -     self._check_banner()
12:38:05 -    ERROR - paramiko.transport -   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1858, in _check_banner
12:38:05 -    ERROR - paramiko.transport -     raise SSHException('Error reading SSH protocol banner' + str(e))
12:38:05 -    ERROR - paramiko.transport - SSHException: Error reading SSH protocol banner
12:38:05 -    ERROR - paramiko.transport - 
12:38:05 -    ERROR - wally           - During connect to 172.17.3.2: timed out
12:38:05 -    ERROR - wally           - During connect to 172.17.3.1: timed out
12:38:05 -    ERROR - wally           - During connect to 172.17.3.3: timed out
12:38:05 -    ERROR - wally           - During connect to 172.17.1.1: timed out
12:38:05 -    ERROR - wally           - During connect to root@172.17.1.1::/root/.ssh/id_rsa: timed out
12:38:05 -    ERROR - paramiko.transport - Exception: Error reading SSH protocol banner
12:38:05 -    ERROR - paramiko.transport - Traceback (most recent call last):
12:38:05 -    ERROR - paramiko.transport -   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1710, in run
12:38:05 -    ERROR - paramiko.transport -     self._check_banner()
12:38:05 -    ERROR - paramiko.transport -   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1858, in _check_banner
12:38:05 -    ERROR - paramiko.transport -     raise SSHException('Error reading SSH protocol banner' + str(e))
12:38:05 -    ERROR - paramiko.transport - SSHException: Error reading SSH protocol banner
12:38:05 -    ERROR - paramiko.transport - 
12:38:05 -    ERROR - wally           - During connect to 172.17.1.2: Error reading SSH protocol banner
12:38:06 -    ERROR - paramiko.transport - Exception: Error reading SSH protocol banner
12:38:06 -    ERROR - paramiko.transport - Traceback (most recent call last):
12:38:06 -    ERROR - paramiko.transport -   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1710, in run
12:38:06 -    ERROR - paramiko.transport -     self._check_banner()
12:38:06 -    ERROR - paramiko.transport -   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1858, in _check_banner
12:38:06 -    ERROR - paramiko.transport -     raise SSHException('Error reading SSH protocol banner' + str(e))
12:38:06 -    ERROR - paramiko.transport - SSHException: Error reading SSH protocol banner
12:38:06 -    ERROR - paramiko.transport - 
12:38:06 -    ERROR - wally           - During connect to 172.17.1.3: Error reading SSH protocol banner
12:38:07 -  WARNING - wally           - Node(s) 172.17.3.1:22,172.17.3.3:22,172.17.3.2:22,172.17.1.3:22,172.17.1.2:22,172.17.1.1:22 would be excluded - can't connect
12:38:07 -    ERROR - wally           - Can't connect to testnode(s) 172.17.1.1:22
12:38:07 -    ERROR - wally           - Exception during connect_stage: Can't connect to testnode(s) 172.17.1.1:22
12:38:07 -     INFO - wally           - Start disconnect_stage
12:38:07 -    DEBUG - wally           - Start utils.cleanup
12:38:07 -     INFO - wally           - All info stored into /var/wally_results/tamest_charlotte
12:38:07 -    ERROR - wally           - Tests are failed. See detailed error above
